# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    curl -o rustup-init.sh https://sh.rustup.rs -sSf
    sh rustup-init.sh -y
  displayName: 'Install Rust'

- script: |
    sudo apt-get install openssl-devel libpq-dev -y
  displayName: 'Install Dependencies'

- script: |
    source $HOME/.cargo/env
    echo 'Agent ID $(Agent.Id)'
    echo 'Agent Name $(Agent.Name)'
    echo 'Agent MachineName $(Agent.MachineName)'
    echo 'Agent OS $(Agent.OS)'

    echo 'Build ID $(Build.BuildId)'
    echo 'Build Number $(Build.BuildNumber)'

    export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
    export OPENSSL_STATIC=1
    echo 'LD_LIBRARY_PATH $LD_LIBRARY_PATH'
    printenv LD_LIBRARY_PATH

    cargo build --release --verbose
  displayName: 'Build sushii'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'target/release/sushii'
    artifactName: 'sushii-$(Build.BuildNumber)-$(Agent.OS)'
